remote_theme: coursweb/jk-theme
title: Cours Figma
description: Un cours sur l'utilisation de Figma.
lang: fr-FR
chapters:
 - title: Cours-web
   url: https://cours-web.ch/
 - title: Git
   url: https://cours-web.ch/git/
# Content is split in three columns.   
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2018–2022</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/coursweb/figma">Lien Github</a></li></ul>